In [156]:
import pandas as pd

In [157]:
df1 = pd.read_excel('C://Users//DanukaDilshanRathnay//Desktop//AI-Driven-Job-Role-Fit-Prediction//code//Dataset//Similarity_with_EMP_data.xlsx')
df1.head()

,EmployeeCode,Technical Score_JD,Programming Score_JD,Soft Score_with_JD,Education_match_Score_with_JD,Gender,Age,Department,JobCategory,ProficiencyLevel,...,Total Experience in Years,Number of Goal Assigned,Number of Goals Achieved,Final Score,Goals Score,Competency Score,Cultural Value Score,Additional Accomplishment Score,Potential Assessment Score,Trait Assessment Score
0,EMP9004,0.257062,0.667620,0.468664,0.573545,Male,41,Data and AI,Data Scientist,Senior,...,19,10,7,35.000000,70.000000,34.180251,76.488103,7.08,51.806653,55.141563
1,EMP9005,0.171806,0.543745,0.468005,0.648808,Female,33,Data and AI,Data Engineer,Mid-Level,...,11,10,5,35.000000,50.000000,30.775600,63.895969,1.63,40.425636,54.988743
2,EMP9009,0.237569,0.667620,0.509374,0.675198,Male,35,Data and AI,Data Scientist,Mid-Level,...,13,7,3,35.000000,42.857143,20.708582,57.979997,8.01,30.443135,36.977535
3,EMP9015,0.253079,0.646303,0.453373,0.634185,Male,42,Data and AI,Data Scientist,Senior,...,20,10,5,35.000000,50.000000,18.998407,66.495545,5.71,43.893732,45.595596
4,EMP9021,0.163569,0.646303,0.418016,0.721195,Male,59,Data and AI,Data Analyst,Expert,...,37,15,11,56.717347,73.333333,32.126666,78.174790,2.63,61.771810,50.283365

In [158]:
employee_ids = df1["EmployeeCode"]

df = df1.drop(columns=["EmployeeCode"])

In [159]:
un_col=['Gender','Department', 'JobCategory', 'ProficiencyLevel',
       'Education Qualifications', 'Professional Qualifications','Final Score','Age','List of Software Skills','Number of Goal Assigned', 'Number of Goals Achieved','Projects Completed',"Total Experience in Years","Absentism Rate"]
df_n=df.drop(columns=un_col)

In [160]:
df_n.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 14 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Technical Score_JD                      240 non-null    float64
 1   Programming Score_JD                    240 non-null    float64
 2   Soft Score_with_JD                      240 non-null    float64
 3   Education_match_Score_with_JD           240 non-null    float64
 4   Years of Experience in this Company     240 non-null    int64
 5   KPI                                     240 non-null    float64
 6   Employee Satisfaction Score             240 non-null    float64
 7   Experience in Years Previous Positions  240 non-null    int64
 8   Goals Score                             240 non-null    float64
 9   Competency Score                        240 non-null    float64
 10  Cultural Value Score                    240 non-null    float64
 11  Additional Accomplishment Score         240 non-null    float64
 12  Potential Assessment Score              240 non-null    float64
 13  Trait Assessment Score                  240 non-null    float64
dtypes: float64(12), int64(2)
memory usage: 26.4 KB

In [161]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler
sd=StandardScaler()
mn=MinMaxScaler()
df_con=sd.fit_transform(df_n)
df_con=pd.DataFrame(df_con,columns=df_n.columns)
df_con.head()

,Technical Score_JD,Programming Score_JD,Soft Score_with_JD,Education_match_Score_with_JD,Years of Experience in this Company,KPI,Employee Satisfaction Score,Experience in Years Previous Positions,Goals Score,Competency Score,Cultural Value Score,Additional Accomplishment Score,Potential Assessment Score,Trait Assessment Score
0,0.513790,0.646515,0.741535,-0.880730,-0.590303,-0.233031,0.276858,0.597193,0.639453,0.728677,0.884639,0.656303,0.436509,0.462198
1,-0.919798,-0.451721,0.733751,0.312989,-0.455248,-0.471827,-1.028983,-0.516742,-0.396366,0.357783,-0.461913,-1.204903,-0.334448,0.444873
2,0.186014,0.646515,1.222497,0.731556,-0.995468,-1.425184,0.269708,0.225881,-0.766302,-0.738894,-1.094544,0.973903,-1.010668,-1.597004
3,0.446811,0.457528,0.560877,0.081058,-0.995468,-1.265382,-0.666101,1.092276,-0.396366,-0.925196,-0.183925,0.188440,-0.099517,-0.620000
4,-1.058308,0.457528,0.143155,1.461114,0.625192,1.658107,1.505833,1.711129,0.812089,0.504965,1.065007,-0.863398,1.111555,-0.088562

### Use PCA to create new dataset

In [162]:
from sklearn.decomposition import PCA
import numpy as np
import matplotlib.pyplot as plt

In [163]:
pca=PCA(n_components=0.90)
df_pca=pca.fit_transform(df_con)

In [164]:
eigenvalues=pca.explained_variance_
print(eigenvalues)

[3.65911996 2.43917849 1.4046136  1.17700872 1.01807232 1.00041382
 0.94461265 0.71108706 0.65672666]

In [165]:
df_pca.shape

(240, 9)

### apply this careted data set into Auto encoder

In [166]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Model
from sklearn.preprocessing import MinMaxScaler,StandardScaler
from sklearn.model_selection import train_test_split
import joblib
from tensorflow.keras.layers import Input, Dense, Dropout, BatchNormalization
from tensorflow.keras import regularizers
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.optimizers import Adam
import keras_tuner as kt
import random

SEED = 42
np.random.seed(SEED)
tf.random.set_seed(SEED)
random.seed(SEED)

In [167]:
df_pca=mn.fit_transform(df_pca)

In [168]:
X_train, X_test = train_test_split(df_pca, test_size=0.3, random_state=SEED)

In [169]:
from keras.regularizers import l2, l1
import keras_tuner as kt

def build_autoencoder(hp):
    input_dim = X_train.shape[1]
    encoding_dim = hp.Int("encoding_dim", min_value=2, max_value=max(4, input_dim // 2), step=1)  # Reduced max_value

    # Regularization strength hyperparameters (more conservative range)
    l2_reg = hp.Float("l2_reg", min_value=1e-6, max_value=1e-4, sampling="log")
    dropout_rate = hp.Float("dropout_rate", min_value=0.05, max_value=0.2, step=0.05)
    l1_reg = hp.Float("l1_reg", min_value=1e-6, max_value=1e-4, sampling="log")  # Sparsity regularization

    input_layer = Input(shape=(input_dim,))

    # First hidden layer with L2 regularization and dropout
    # Fewer units in the first layer
    encoded = Dense(hp.Int("units1", min_value=4, max_value=32, step=4),
                    activation=hp.Choice("activation1", ["relu", "tanh"]),
                    kernel_regularizer=l2(l2_reg))(input_layer)
    encoded = Dropout(dropout_rate)(encoded)

    # Latent space with L1 sparsity constraint
    encoded = Dense(encoding_dim, activation="relu", activity_regularizer=l1(l1_reg))(encoded)

    # Decoder with L2 regularization and dropout
    # Simpler decoder
    decoded = Dense(hp.Int("units2", min_value=4, max_value=32, step=4),
                    activation=hp.Choice("activation2", ["relu", "tanh"]),
                    kernel_regularizer=l2(l2_reg))(encoded)
    decoded = Dropout(dropout_rate)(decoded)
    decoded = Dense(input_dim, activation="sigmoid")(decoded)

    autoencoder = Model(input_layer, decoded)
    autoencoder.compile(optimizer=Adam(learning_rate=hp.Choice("learning_rate", [0.001, 0.0005, 0.0001])),
                        loss="mse")

    return autoencoder

# Hyperparameter tuning with Keras Tuner
tuner = kt.RandomSearch(
    build_autoencoder,
    objective="val_loss",
    max_trials=5,  # Fewer trials to prevent excessive fitting to the small dataset
    executions_per_trial=1,  # Reduce the number of executions to minimize variance effects
    directory="autoencoder_tuning_hy",
    project_name="employee_autoencoder_hy"
)

# Search for the best hyperparameters
tuner.search(X_train, X_train, epochs=20, batch_size=8, validation_data=(X_test, X_test))

Reloading Tuner from autoencoder_tuning_hy\employee_autoencoder_hy\tuner0.json

In [170]:
# Get the best hyperparameters
best_hps = tuner.get_best_hyperparameters(num_trials=1)[0]
print(f"Best Encoding Dim: {best_hps.get('encoding_dim')}")
print(f"Best Layer 1 Units: {best_hps.get('units1')}, Activation: {best_hps.get('activation1')}")
print(f"Best Layer 2 Units: {best_hps.get('units2')}, Activation: {best_hps.get('activation2')}")
print(f"Best Learning Rate: {best_hps.get('learning_rate')}")

# Train Autoencoder with best hyperparameters
best_autoencoder = tuner.hypermodel.build(best_hps)
history = best_autoencoder.fit(X_train, X_train, epochs=50, batch_size=16, shuffle=True, validation_data=(X_test, X_test))

# Extract Encoder Model
encoder = Model(best_autoencoder.input, best_autoencoder.layers[1].output)  # Extract latent space representation

# Generate latent space representation (Employee Scores)
employee_scores = encoder.predict(df_pca)

Best Encoding Dim: 3
Best Layer 1 Units: 8, Activation: relu
Best Layer 2 Units: 28, Activation: tanh
Best Learning Rate: 0.001
Epoch 1/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0381 - val_loss: 0.0396
Epoch 2/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0357 - val_loss: 0.0380
Epoch 3/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0337 - val_loss: 0.0371
Epoch 4/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0331 - val_loss: 0.0367
Epoch 5/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0328 - val_loss: 0.0365
Epoch 6/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0327 - val_loss: 0.0364
Epoch 7/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0323 - val_loss: 0.0363
Epoch 8/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0322 - val_loss: 0.0362
Epoch 9/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0322 - val_loss: 0.0360
Epoch 10/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0320 - val_loss: 0.0359
Epoch 11/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0315 - val_loss: 0.0357
Epoch 12/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0316 - val_loss: 0.0355
Epoch 13/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0314 - val_loss: 0.0354
Epoch 14/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0311 - val_loss: 0.0352
Epoch 15/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0309 - val_loss: 0.0351
Epoch 16/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0308 - val_loss: 0.0350
Epoch 17/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0309 - val_loss: 0.0348
Epoch 18/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0304 - val_loss: 0.0346
Epoch 19/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0305 - val_loss: 0.0345
Epoch 20/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0299 - val_loss: 0.0343
Epoch 21/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0302 - val_loss: 0.0342
Epoch 22/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0299 - val_loss: 0.0340
Epoch 23/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0298 - val_loss: 0.0339
Epoch 24/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0300 - val_loss: 0.0338
Epoch 25/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0296 - val_loss: 0.0336
Epoch 26/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0294 - val_loss: 0.0335
Epoch 27/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0291 - val_loss: 0.0334
Epoch 28/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0293 - val_loss: 0.0332
Epoch 29/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0294 - val_loss: 0.0331
Epoch 30/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0286 - val_loss: 0.0331
Epoch 31/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0289 - val_loss: 0.0330
Epoch 32/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0285 - val_loss: 0.0329
Epoch 33/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0290 - val_loss: 0.0328
Epoch 34/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0284 - val_loss: 0.0327
Epoch 35/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0285 - val_loss: 0.0326
Epoch 36/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0284 - val_loss: 0.0325
Epoch 37/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0283 - val_loss: 0.0323
Epoch 38/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0281 - val_loss: 0.0320
Epoch 39/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0276 - val_loss: 0.0316
Epoch 40/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0275 - val_loss: 0.0313
Epoch 41/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0274 - val_loss: 0.0309
Epoch 42/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0272 - val_loss: 0.0307
Epoch 43/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0269 - val_loss: 0.0304
Epoch 44/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0268 - val_loss: 0.0301
Epoch 45/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0268 - val_loss: 0.0299
Epoch 46/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0268 - val_loss: 0.0297
Epoch 47/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0269 - val_loss: 0.0295
Epoch 48/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0269 - val_loss: 0.0293
Epoch 49/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0266 - val_loss: 0.0291
Epoch 50/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0262 - val_loss: 0.0290
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step

In [171]:
for i in range(employee_scores.shape[1]):
    df[f'LatentFeature_{i+1}'] = employee_scores[:, i]

In [172]:
df['SuitabilityScore_AE(Hybrid)'] = np.abs(df[[f'LatentFeature_{i+1}' for i in range(employee_scores.shape[1])]]).mean(axis=1)

In [173]:
df.head()

,Technical Score_JD,Programming Score_JD,Soft Score_with_JD,Education_match_Score_with_JD,Gender,Age,Department,JobCategory,ProficiencyLevel,Education Qualifications,...,Trait Assessment Score,LatentFeature_1,LatentFeature_2,LatentFeature_3,LatentFeature_4,LatentFeature_5,LatentFeature_6,LatentFeature_7,LatentFeature_8,SuitabilityScore_AE(Hybrid)
0,0.257062,0.667620,0.468664,0.573545,Male,41,Data and AI,Data Scientist,Senior,"Bachelor of Statistics, Master of Data Analytics",...,55.141563,0.0,0.226524,0.312301,0.426260,0.517044,0.0,0.0,0.0,0.185266
1,0.171806,0.543745,0.468005,0.648808,Female,33,Data and AI,Data Engineer,Mid-Level,Bachelor of Science,...,54.988743,0.0,0.477506,0.374318,0.131855,0.462098,0.0,0.0,0.0,0.180722
2,0.237569,0.667620,0.509374,0.675198,Male,35,Data and AI,Data Scientist,Mid-Level,"Bachelor of Data Science, Master of Data Science",...,36.977535,0.0,0.454671,0.233297,0.119345,0.501342,0.0,0.0,0.0,0.163582
3,0.253079,0.646303,0.453373,0.634185,Male,42,Data and AI,Data Scientist,Senior,"Bachelor of Applied Statistics, Master of Data...",...,45.595596,0.0,0.497718,0.298987,0.234830,0.364235,0.0,0.0,0.0,0.174471
4,0.163569,0.646303,0.418016,0.721195,Male,59,Data and AI,Data Analyst,Expert,"Bachelor of Data Science, Master of Data Scien...",...,50.283365,0.0,0.527964,0.387335,0.242974,0.333884,0.0,0.0,0.0,0.186520

In [174]:
df1=pd.read_excel("C://Users//DanukaDilshanRathnay//Desktop//AI-Driven-Job-Role-Fit-Prediction//code//Dataset//Jd_score.xlsx")
df3=pd.read_excel("C://Users//DanukaDilshanRathnay//Desktop//AI-Driven-Job-Role-Fit-Prediction//code//PCA_score.xlsx")
df1=df1[['EmployeeCode','JD match Score']]
df1['Job_disimilarity']=1-df1['JD match Score']
df3=df3[['EmployeeCode','Suitability_score_scaled_PCA']]
df4=pd.read_excel("C://Users//DanukaDilshanRathnay//Desktop//AI-Driven-Job-Role-Fit-Prediction//code//abc.xlsx")

In [175]:
dfAEh = pd.concat([employee_ids.reset_index(drop=True), df], axis=1)

In [176]:
dfAEh=dfAEh[['EmployeeCode','SuitabilityScore_AE(Hybrid)']]

In [177]:
df4.columns

Index(['EmployeeCode', 'JD match Score', 'Job_disimilarity',
       'Suitability_score_scaled_PCA', 'SuitabilityScore_AE'],
      dtype='object')

In [178]:
df6=df4.merge(dfAEh,on='EmployeeCode')

In [179]:
df6[['Job_disimilarity','Suitability_score_scaled_PCA', 'SuitabilityScore_AE(Hybrid)','SuitabilityScore_AE']].corr()

,Job_disimilarity,Suitability_score_scaled_PCA,SuitabilityScore_AE(Hybrid),SuitabilityScore_AE
Job_disimilarity,1.000000,-0.230778,-0.318178,-0.209490
Suitability_score_scaled_PCA,-0.230778,1.000000,0.424658,0.907016
SuitabilityScore_AE(Hybrid),-0.318178,0.424658,1.000000,0.258309
SuitabilityScore_AE,-0.209490,0.907016,0.258309,1.000000